version: '3.7'

services:
  db:
    container_name: reignstore
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: "reign_challege"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "reign"
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - nosqldata:/data/db
  server:
    container_name: serverApi
    build:
      context: ./server
      dockerfile: Dockerfile
    links: 
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./client:/usr/src/app
volumes:
  nosqldata:
