version: '3.7'

services:
  db:
    container_name: reignstore
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: "reign_challege"
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodb:/data/db
  server:
    container_name: serverApi
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    links: 
      - db
    environment: 
      - DB_URL=mongodb://reignstore/reign_challege
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /urs/src/app/node_modules
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./client:/usr/src/app
volumes:
  mongodb:
